name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          ssh -tt -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ~/rate-music-app
            cat > .env << EOL
            # Backend Variables
            VITE_DATABASE_URL=${{ secrets.VITE_DATABASE_URL }}
            VITE_PORT=4960
            VITE_JWT_SECRET='supersecret'

            # Frontend Variables
            VITE_API_URL=http://localhost:4960/api
            EOL
          EOF

      - name: Pull latest code
        run: |
          ssh -tt -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} 'cd ~/rate-music-app && git pull origin main'

      - name: Install dependencies
        run: |
          ssh -tt -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ~/rate-music-app
            npm install
            cd frontend && npm install
            cd ../backend && npm install
          EOF

      - name: Run tests
        run: |
          ssh -tt -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} 'cd ~/rate-music-app && npm run test'

      - name: Restart application
        run: |
          ssh -tt -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ~/rate-music-app
            pkill -f "npm run dev" || true
            pkill -f "node.*rate-music-app" || true
            
            if command -v pm2 &> /dev/null; then
              pm2 stop rate-music-app || true
              pm2 start npm --name "rate-music-app" -- run dev
              pm2 save
            else
              nohup npm run dev > app.log 2>&1 &
            fi
            
            echo "Deployment completed successfully"
          EOF

      - name: Cleanup SSH Key
        if: always()
        run: |
          rm -f ~/.ssh/deploy_key