name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into Azure VM and deploy
        run: |
          ssh -tt ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ~/your-app-folder  # 👈 change this to your actual app folder

            # Create .env file at root
            cat > .env <<EOL
            # Backend Variables
            VITE_DATABASE_URL=postgresql://postgres.tqpoprazhxkebxnwtuve:c7Law7gQ7NS*ENf@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
            VITE_DATABASE_URL= ${{secrets.VITE_DATABASE_URL}}
            VITE_PORT=4960
            VITE_JWT_SECRET='supersecret'

            # Frontend Variables
            VITE_API_URL=http://localhost:4960/api
            EOL

            # Pull latest code
            git pull origin main

            # Install dependencies
            npm install

            # Run tests
            npm run test

            # Start app (use something like pm2 or tmux to keep it alive)
            pkill node || true  # kill previous dev if running
            nohup npm run dev > app.log 2>&1 &
          EOF
