name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into Azure VM and deploy
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ~/rate-music-app

            # Create .env file at root
            cat > .env << EOL
            # Backend Variables
            VITE_DATABASE_URL=${{ secrets.VITE_DATABASE_URL }}
            VITE_PORT=4960
            VITE_JWT_SECRET='supersecret'

            # Frontend Variables
            VITE_API_URL=http://localhost:4960/api
            EOL

            # Pull latest code
            git pull origin main

            # Install dependencies
            npm install

            cd frontend && npm install && cd ..
            cd backend && npm install && cd ..

            # Run tests
            npm run test

            # Stop existing processes
            pkill -f "npm run dev" || true
            pkill -f "node.*rate-music-app" || true

            # Start app with PM2 (recommended) or nohup
            if command -v pm2 &> /dev/null; then
              pm2 stop rate-music-app || true
              pm2 start npm --name "rate-music-app" -- run dev
              pm2 save
            else
              nohup npm run dev > app.log 2>&1 &
            fi

            echo "Deployment completed successfully"
          EOF

      - name: Cleanup SSH
        if: always()
        run: |
          rm -f ~/.ssh/deploy_key