name: Delete Deployments

on:
  workflow_dispatch:

jobs:
  delete-deployments:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read

    steps:
      - name: Delete all deployments in 'Production'
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: Production
          onlyRemoveDeployments: true
