name: Deploy Azure VM - Rate Music App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Connect via SSH and pull latest code
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 72.145.8.73
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd rate-music-app
            git pull origin main
            npm install
            cd backend
            npm install
            cd ../frontend
            npm install
            cd ../
            pm2 restart rate-music-app
